python grokking/run_grokking_imdb.py \
    --do_train \
    --if_save false \
    --num_labels 2 \
    --dataset_name imdb \
    --model_name_or_path grokking/model_config/one-layer-bert \
    --train_file datasets/IMDB/subdatas/0.3_sub_data/0.6_train.json \
    --test_file datasets/IMDB/test.json \
    --output_dir model/test_reproduce/0.3_sub_data_0.6 \
    --total_steps 7000 \
    --per_device_train_batch_size 128 \
    --per_device_eval_batch_size 1024 \
    --learning_rate 1e-3 \
    --weight_decay 1e-2 \
    --max_length 256 \
    --rescale_num 2 \
    --experiment_name test_reproduce \
    --group_name imdb_grokking